version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/home/pablo/workspace/services-docker/rabbitmq/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/home/pablo/workspace/services-docker/rabbitmq/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/home/pablo/workspace/services-docker/rabbitmq/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672

